# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-18 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileEntity',
            fields=[
                ('hash', models.TextField(max_length=64, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
